version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    restart: always
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.yml:/usr/share/logstash/pipeline/logstash.yml
    ports:
      - 5044:5044

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    restart: always
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
